version: '3.5'
services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:8002 -t public'
    volumes:
          - .:/app
    ports:
      - 8002:8002
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    external: true
