version: '3.5'
services:
  transaction:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:8005 -t public'
    volumes:
          - .:/app
    ports:
      - 8005:8005
    depends_on:
      - transaction_db
    networks:
      - app-network

  transaction_db:
    image: mysql:5.7.22
    container_name: transaction_db
    restart: on-failure
    tty: true
    environment:
      MYSQL_DATABASE: transaction
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    external: true
