version: '3.5'
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:8000 -t public'
    volumes:
          - .:/app
    ports:
      - 8000:8000
    depends_on:
      - user_db

  user_db:
    image: mysql:5.7.22
    container_name: user_db
    restart: on-failure
    tty: true
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33062:3306"
